default_stages: [commit]
repos:
    # - repo: https://github.com/antonbabenko/pre-commit-terraform
    #   rev: v1.77.0
    #   hooks:
    #       - id: terraform_fmt
    #       - id: terraform_validate
    #       - id: terraform_tflint
    #       - id: terraform_tfsec
    #       - id: terraform_checkov
    #         args:
    #           - --args=--download-external-modules true
    #       - id: terraform_docs
    #         args:
    #           - --hook-config=--path-to-file=README.md
    #           - --hook-config=--add-to-existing-file=true
    #           - --hook-config=--create-file-if-not-exist=true
    #       - id: infracost_breakdown
    #         args:
    #         - --args=--path=./
    #         verbose: true
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
