apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-k8s-demo
  namespace: argocd
spec:
  destination:
    namespace: flask-app
    server: https://kubernetes.default.svc
  project: flask-k8s-demo
  source:
    path: argocd/manifests/flask-app
    repoURL: https://github.com/Lendscape-AppMan/flask-eks-demo.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
