server:
  additionalApplications:
   - name: cluster-config
     namespace: argocd
     project: default
     source:
      #  repoURL: https://github.com/piomin/sample-terraform-kubernetes-argocd.git
       repoURL: https://github.com/Lendscape-AppMan/flask-eks-demo.git
       targetRevision: HEAD
       path: argocd/manifests/cluster
       directory:
         recurse: true
     destination:
       server: https://kubernetes.default.svc
     syncPolicy:
       automated:
         prune: false
         selfHeal: false
