apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: argocd
spec:
  project: flask-app-project
  source:
    repoURL: https://github.com/my-repo.git
    targetRevision: HEAD
  destination:
    namespace: flask-app
    server: https://kubernetes.default.svc
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true